


// var fruits = ["Apple","Banana","Bluebarry","Peach","Chery","Guava"]
// var students = ["Adib","Yann","Rohan","Adnan","Araf","Raian","Rupantur","Arhgay",]

// var number = [34,27,5,7,10,56]


// // console.log(color);

// // console.log(fruits[0]);
// // console.log(fruits[1]);
// // console.log(fruits[2]);


// var color =["Red","Blue","Yellow","Green"]

// // console.log(color);
// color.push("Gray")
// color.push("Pink")
// color.push("Black")
// color.push("Sky Blue")

// // console.log(color);

// console.log(color);
// color.pop()
// color.pop()
// color.pop()
// color.pop()
// console.log(color);


var students = ["Adib","Yann","Rohan","Adnan","Araf","Raian","Rupantur","Arhgay",]

students.forEach((mystudent)=>{console.log(mystudent)})

